### ISSUE TITLE
findimagedupes --help errors

### ISSUE THREAD

**Issue by tenzap** [jhnc/findimagedupes#11]
Run `findimagedupes --help`

Last line returns `version` instead of `--version`

```

    -v, --verbosity=LIST
            Enable display of informational messages to stdout, where LIST
            is a comma-delimited list of:

            md5     Display the checksum for each file, as per md5sum(1).

            fingerprint | fp
                    Display the base64-encoded fingerprint of each file.

            Alternatively, --verbosity may be given multiple times, and
            accumulates. Note that this may not be sensible. For example, to
            be useful, md5 output probably should not be merged with
            fingerprint data.

    version Display the program version, then exit.
```

Moreover, exit code of `findimagedupes --help` is 1, is this expected?

Finally `findimagedupes --version` doesn't print the version, just the name.

OS: Macos, v2.20.1

**Comment by jhnc** [comment]
Thank you for the report. The typo is fixed in git but I haven't tagged a new release yet.

Exit codes are documented at: https://github.com/jhnc/findimagedupes#return-value

The version is obtained from git and patched into the program. If you are using a version someone else packaged, you should let them know (eg. debian recently fixed their build process).

If you are building yourself, you'll need to perform a similar process to that done by the `Makefile` and `patchver` script (or just edit the variable manually):
https://github.com/jhnc/findimagedupes/blob/34dd0dc389de1e9ed9625034e5fa710d44d15d41/Makefile#L26-L27
https://github.com/jhnc/findimagedupes/blob/34dd0dc389de1e9ed9625034e5fa710d44d15d41/patchver#L3

**Comment by tenzap** [comment]
Oh ok, thanks. I checked exit codes but wasn't careful enough.

I just took the raw file from github on a tag without any other change.
Well, I did some changes, especially DIRECTORY and the shebang to `/usr/bin/env perl`

Actually I was installing this way:  https://github.com/jhnc/findimagedupes/issues/8#issuecomment-1418903291

**Comment by jhnc** [comment]
Thanks for providing your install notes. Hopefully they will help someone. :thumbsup:

If you are just pulling the raw file, you could parameterise the tag version to a variable in your script and then also use it in an extra `gsed` line that does the equivalent of `patchver`. (All the `gsed` commands can be a single invocation.) For example:

```
VERSION=2.20.1
# ...
wget https://raw.githubusercontent.com/jhnc/findimagedupes/$VERSION/findimagedupes
# ..
gsed -i "
    /^#\!/s#perl#env &#
    /DIRECTORY =>/s#'.*'#\$ENV{HOME}#
    /my \$Id/s#'.*'#'$VERSION'#
" findimagedupes
# ...
```
