### ISSUE TITLE
request: findimagedupes can be used also for comparing similarity of videos

### ISSUE THREAD

**Issue by estatistics** [jhnc/findimagedupes#15]
request: findimagedupes can be used also for comparing similarity of videos

By reading this: [https://unix.stackexchange.com/questions/503060/evaluate-the-similarity-between-two-video-files](url)
i can image that using ffmpeg you can extract first/last frame of two video files and then get a similarity between these two frames of these two videos.

I think this is an incredible idea! No such tool exists in whole web! 

What do you say?

**Comment by jhnc** [comment]
It's certainly an interesting idea but there would be many complications which I am probably not competent to overcome.

I think it would need many more than just two images (consider what happens if you happen to select an all black image) . So likely to be very slow using the current findimagedupes implementation.

Trivial differences in video length (equivalent to cropping an image) or scene insertion (eg.  one version contains advertisements) would probably prevent a match.

There may be situations where an idea like this works very well but I suspect the results could become terrible if the use case was altered evn slightly.  I see someone wrote this:
https://openwritings.net/pg/linux/linux-find-duplicate-video - presumably it works for them?)

I'm going to close this as "not planned" but thank you for the suggestion.
