### ISSUE TITLE
HEIC Support - iPhone Pictures

### ISSUE THREAD

**Issue by Tobix99** [jhnc/findimagedupes#2]
Hey,

is it possible to easily add a HEIC support for comparision? If I've time I can also look into it, but tight now I have to study for my exams.

Does imagemagick even support HEIC?

**Comment by jhnc** [comment]
findimagedupes uses graphicsmagick, not imagemagick, and the graphicsmagick maintainer appears uninterested in supporting HEIC: https://sourceforge.net/p/graphicsmagick/discussion/250738/thread/3082583888/

imagemagick version 7 seems to support HEIC. Unfortunately, at this time, distributions seem mostly to include version 6 (without HEIC support). If version 7 becomes readily available, I may consider switching findimagedupes to use it instead of graphicsmagick.

**Comment by tuomaz** [comment]
There have been some updates in the referenced thread at Sourceforge

**Comment by jhnc** [comment]
@tuomaz Thanks for the heads up.
Hopefully HEIC support is coming to graphicsmagick :)

**Comment by jhnc** [comment]
Closing. (sufficiently recent) graphicsmagick can now be built to support HEIC.
